// SPDX-FileCopyrightText: 2024 Cesanta Software Limited
// SPDX-License-Identifier: GPL-2.0-only or commercial
// Generated by Mongoose Wizard, https://mongoose.ws/wizard/

// Default mock implementation of the API callbacks

#include "mongoose_glue.h"
static uint64_t s_action_timeout_reboot;  // Time when reboot ends
bool glue_check_reboot(void) {
  return s_action_timeout_reboot > mg_now(); // Return true if reboot is in progress
}
void glue_start_reboot(struct mg_str params) {
  MG_DEBUG(("Passed parameters: [%.*s]", params.len, params.buf));
  s_action_timeout_reboot = mg_now() + 1000; // Start reboot, finish after 1 second
}

void *glue_ota_begin_firmware_update(char *file_name, size_t total_size) {
  bool ok = mg_ota_begin(total_size);
  MG_DEBUG(("%s size %lu, ok: %d", file_name, total_size, ok));
  return ok ? (void *) 1 : NULL;
}
bool glue_ota_end_firmware_update(void *context) {
  mg_timer_add(&g_mgr, 500, 0, (void (*)(void *)) (void *) mg_ota_end, context);
  return true;
}
bool glue_ota_write_firmware_update(void *context, void *buf, size_t len) {
  MG_DEBUG(("ctx: %p %p/%lu", context, buf, len));
  return mg_ota_write(buf, len);
}

static struct settings s_settings = {false, "60ms-F9P", 192, 168, 5, 126, "AiO v5.0d Web GUI - Feb 11 2025 13:47:11"};
void glue_get_settings(struct settings *data) {
  *data = s_settings;  // Sync with your device
}
void glue_set_settings(struct settings *data) {
  s_settings = *data; // Sync with your device
}

static struct kwas_cfg s_kwas_cfg = {false, 0.1, 0.5, 3, 0.1, 0.0001, 2};
void glue_get_kwas_cfg(struct kwas_cfg *data) {
  *data = s_kwas_cfg;  // Sync with your device
}
void glue_set_kwas_cfg(struct kwas_cfg *data) {
  s_kwas_cfg = *data; // Sync with your device
}

static struct ins_cfg s_ins_cfg = {"MODE ROVER SURVEY", "CONFIG INS TIMEOUT 60", "CONFIG INS ALIGNMENTVEL 1.5", "CONFIG INSDIRECTION AUTO", "CONFIG RTK TIMEOUT 120", "CONFIG RTK RELIABILITY 3 1", "CONFIG SIGNALGROUP 1", "CONFIG COM1 460800", "CONFIG COM2 460800", "CONFIG COM3 460800", "GNGGA COM3 0.1", "GPVTG COM3 0.1", "INSPVAXA COM3 0.1", "CONFIG INS ANGLE 0.00 0.00 0.00", "CONFIG IMUTOANT OFFSET 0.00 0.00 0.00 0.01 0.01 0.01", "CONFIG INSSOL OFFSET 0.00 0.00 0.00"};
void glue_get_ins_cfg(struct ins_cfg *data) {
  *data = s_ins_cfg;  // Sync with your device
}
void glue_set_ins_cfg(struct ins_cfg *data) {
  s_ins_cfg = *data; // Sync with your device
}
