// SPDX-FileCopyrightText: 2024 Cesanta Software Limited
// SPDX-License-Identifier: GPL-2.0-only or commercial
// Generated by Mongoose Wizard, https://mongoose.ws/wizard/

// Default mock implementation of the API callbacks

#include "mongoose_glue.h"
static struct logger s_logger = {true, 6, false, 514};
void glue_get_logger(struct logger *data) {
  *data = s_logger;  // Sync with your device
}
void glue_set_logger(struct logger *data) {
  s_logger = *data; // Sync with your device
}

static struct stats s_stats = {0};
void glue_get_stats(struct stats *data) {
  *data = s_stats;  // Sync with your device
}
void glue_set_stats(struct stats *data) {
  s_stats = *data; // Sync with your device
}

void *glue_ota_begin_firmware_update(char *file_name, size_t total_size) {
  bool ok = mg_ota_begin(total_size);
  MG_DEBUG(("%s size %lu, ok: %d", file_name, total_size, ok));
  return ok ? (void *) 1 : NULL;
}
bool glue_ota_end_firmware_update(void *context) {
  mg_timer_add(&g_mgr, 500, 0, (void (*)(void *)) (void *) mg_ota_end, context);
  return true;
}
bool glue_ota_write_firmware_update(void *context, void *buf, size_t len) {
  MG_DEBUG(("ctx: %p %p/%lu", context, buf, len));
  return mg_ota_write(buf, len);
}
